services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: .
    container_name: meu-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "37880:37880"
    env_file:
      - ./.env
    working_dir: /app

volumes:
  mysql_data: