// apiAdmRoutes.js
const express = require('express')
const { body } = require('express-validator')
const router = express.Router()
const apiAdm = require('../controllers/apiAdmController')
const { authenticateToken } = require('../middleware/auth')

router.get('/listClient', apiAdm.listClients)
router.post('/listNewClients', apiAdm.listNewClients)
router.post('/register', apiAdm.registerClient)
router.post('/searchClients', apiAdm.searchClients)
router.patch('/updateClient/:id', apiAdm.patchClient)
router.get('/clientes/:id', apiAdm.getClientById)
router.delete('/deleteAllClientes/:id', apiAdm.deleteClientById)
router.post('/clientes/listSalesByType', apiAdm.listSalesByType)
router.post('/kits', apiAdm.createKit)
router.get('/kits', apiAdm.listKits)
router.get('/kits/:sku', apiAdm.getKitBySku)
router.put('/kits/:sku', apiAdm.updateKit)
router.delete('/kits/:sku', apiAdm.deleteKit)
router.get('/listFrases', apiAdm.listFrases)
router.get('/ativos', apiAdm.getActiveVendors)
router.post('/locationClient', apiAdm.getLocationClient)
router.patch('/updateClientLocation', apiAdm.patchClientLocation)
router.patch('/updateClientCoordinates', apiAdm.updateClientCoordinates)
router.post('/produtos', apiAdm.createProduct)
router.get('/produtos/all', apiAdm.listProduct)
router.get('/produtos/sku/:sku', apiAdm.getProductBySku)
router.get('/produtos/search', apiAdm.searchProductByDescription)
router.put('/produtos/:sku', apiAdm.updateProdutos)
router.get('/dashboard', apiAdm.getInfosDashboard)
router.get('/dashboardDetailed', apiAdm.getDetailedDashboardInfo)
router.delete('/produtos/:sku', apiAdm.deleteProduct)
router.post('/listCitys', apiAdm.listClientsByCity)
router.post('/enviosPanosKits', apiAdm.getEnviosAdm)
router.get('/todosEnvios', apiAdm.getAllEnvios)
router.delete('/deletarEnvios', apiAdm.deleteEnvios)
router.get('/RotaAtual', apiAdm.getRotaAtual)
router.get('/nextRoutes', apiAdm.listNextRoutes)
router.get('/beforeRoutes', apiAdm.listBeforeRoutes)
router.post('/NextRoutesWithComparison', apiAdm.listNextRoutesWithComparison)
router.post('/NextRoutesWith', apiAdm.getNextRoutesWithVendaId)
router.post('/buscarCpfNetrinAdm', apiAdm.buscarCpfNetrin)
router.patch('/updateClientStatus', apiAdm.updateClientStatus)
router.get('/clientStatus/:id', apiAdm.getClientStatus)
router.get('/newClientsMonth', authenticateToken, apiAdm.getNovosClientes)
router.post('/buscarClientePorCpf', apiAdm.buscarClienteCpf)
router.get('/faltandoNoMesPorVendedor', apiAdm.getResumoMensalPorVendedor)
router.post('/resumo-por-rota', apiAdm.getResumoMensalPorRota)
router.post('/clientes-por-rota', apiAdm.getClientesPorRotaEVendedor)
router.get('/clientes-ativos-por-vendedor', apiAdm.getClientesAtivosPorVendedor)
router.post('/clientes-ativos-por-rota', apiAdm.getClientesPorRota)
router.post('/clientes-ativos-com-vendas', apiAdm.getClientesComVendasNF)
router.get('/kit/descricao/:sku', apiAdm.getKitWithDescriptions)
router.get('/ambiente/buscar', apiAdm.getAmbiente)
router.get('/ambiente/buscar', apiAdm.getAmbiente)
router.patch('/ambiente/atualizar', apiAdm.updateAmbiente)

module.exports = router
